"""
Descr: Hold constants that are needed over multiple files
"""
FRAME_RATE = 30

TRACK_AREA_WIDTH = 1024
TRACK_AREA_HEIGHT = 768

ACTION_FORWARD = 0
ACTION_BACKWARD = 1
ACTION_LEFT = 2
ACTION_RIGHT = 3
ACTION_NOTHING = 4

TOP_LEFT = (0, 0)

MAX_VEL = 15
MIN_VEL = 0
TURN_RATE = 3
FORWARD_ACCEL = 0.15
BACKWARD_ACCEL = 0.75
SENSOR_MAX = 75

GAME_LENGTH = 1000
